// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/DamienFontaine/lunarc/security (interfaces: ApplicationManager)

package mock

import (
	security "github.com/DamienFontaine/lunarc/security"
	gomock "github.com/golang/mock/gomock"
)

// Mock of ApplicationManager interface
type MockApplicationManager struct {
	ctrl     *gomock.Controller
	recorder *_MockApplicationManagerRecorder
}

// Recorder for MockApplicationManager (not exported)
type _MockApplicationManagerRecorder struct {
	mock *MockApplicationManager
}

func NewMockApplicationManager(ctrl *gomock.Controller) *MockApplicationManager {
	mock := &MockApplicationManager{ctrl: ctrl}
	mock.recorder = &_MockApplicationManagerRecorder{mock}
	return mock
}

func (_m *MockApplicationManager) EXPECT() *_MockApplicationManagerRecorder {
	return _m.recorder
}

func (_m *MockApplicationManager) GetByClientID(_param0 string) (security.Application, error) {
	ret := _m.ctrl.Call(_m, "GetByClientID", _param0)
	ret0, _ := ret[0].(security.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockApplicationManagerRecorder) GetByClientID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetByClientID", arg0)
}
